### ISSUE TITLE
Is it possible to stream output?

### ISSUE THREAD

**Issue by asmith26** [Avaiga/demo-chatbot#6]
Hi Taipy/ @AlexandreSajus ,

Just wondering is it possible to stream the output from an LLM to the GUI/chat message?

Many thanks for any help, and this lib! :)

**Comment by AlexandreSajus** [comment]
It should be possible. What is your exact use case? If the use case is sending prompts and receiving responses from an LLM hosted somewhere, take a look at this tutorial: https://docs.taipy.io/en/latest/tutorials/visuals/5_multithreading/

**Comment by DeveloperVaibhav1** [comment]
check the about for more details read exact dcumentation such as taipylib usecases in py ...

**Comment by DeveloperVaibhav1** [comment]
TAIPY is very good library . Its has lots of work cases.
